map $http_x_forwarded_proto $php_https {
    "https" "on";
    default "";
}

server {
    listen 80;
    server_name _;
    root /var/www/public;
    index index.php;

    charset utf-8;
    client_max_body_size 40M;

    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    location = /favicon.ico { access_log off; log_not_found off; }
    location = /robots.txt  { access_log off; log_not_found off; }

    location = /build/sw.js {
        root /var/www/public;
        add_header Cache-Control "no-cache, no-store, must-revalidate";
        add_header Service-Worker-Allowed "/";
    }

    location ~* \.webmanifest$ {
        root /var/www/public;
        add_header Content-Type "application/manifest+json";
        add_header Cache-Control "no-cache";
    }

    error_page 404 /index.php;

    location ~ \.php$ {
        fastcgi_pass backend:9000;
        fastcgi_param SCRIPT_FILENAME $realpath_root$fastcgi_script_name;
        fastcgi_param HTTPS $php_https;
        fastcgi_param HTTP_HOST $http_host;
        include fastcgi_params;
        fastcgi_hide_header X-Powered-By;
    }

    location ~ /\.(?!well-known).* {
        deny all;
    }
}
